[
  {
    "captures": {
      "return": {
        "staticFields": {
          "Empty": {
            "type": "EmptyResult",
            "value": "EmptyResult"
          }
        },
        "throwable": {
          "message": "recursion exception depth 5",
          "type": "System.Exception",
          "stacktrace": [
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "<runtime>": "<scrubbed>"
            }
          ]
        },
        "locals": {
          "@exception": {
            "type": "Exception",
            "value": "Exception",
            "fields": {
              "Message": {
                "type": "String",
                "value": "recursion exception depth 5"
              },
              "InnerException": {
                "type": "Exception",
                "isNull": "true"
              },
              "HelpLink": {
                "type": "String",
                "isNull": "true"
              },
              "Source": {
                "type": "String",
                "value": "app"
              },
              "HResult": {
                "type": "Int32",
                "value": "-2146233088"
              },
              "StackTrace": {
                "type": "String",
                "value": "<scrubbed>"
              }
            }
          }
        },
        "arguments": {
          "depth": {
            "type": "Int32",
            "value": "5"
          },
          "this": {
            "type": "ExceptionReplayController",
            "value": "ExceptionReplayController"
          }
        }
      }
    },
    "probe": {
      "id": "<scrubbed>",
      "version": 1,
      "location": {
        "method": "exceptionReplayRecursion",
        "type": "weblog.ExceptionReplayController"
      }
    },
    "stack": [
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursion",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 28
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware+<Invoke><scrubbed>",
        "lineNumber": 0
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware.Invoke",
        "lineNumber": 0
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "exceptionHash": "a72525ef-dc75-3a29-abc5-e7f2574a18ab",
    "exceptionId": "<scrubbed>",
    "frameIndex": "6",
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "duration": "<scrubbed>",
    "language": "dotnet"
  },
  {
    "captures": {
      "return": {
        "staticFields": {
          "Empty": {
            "type": "EmptyResult",
            "value": "EmptyResult"
          }
        },
        "throwable": {
          "message": "recursion exception depth 5",
          "type": "System.Exception",
          "stacktrace": [
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursion",
              "lineNumber": 0
            },
            {
              "<runtime>": "<scrubbed>"
            }
          ]
        },
        "locals": {
          "@exception": {
            "type": "Exception",
            "value": "Exception",
            "fields": {
              "Message": {
                "type": "String",
                "value": "recursion exception depth 5"
              },
              "InnerException": {
                "type": "Exception",
                "isNull": "true"
              },
              "HelpLink": {
                "type": "String",
                "isNull": "true"
              },
              "Source": {
                "type": "String",
                "value": "app"
              },
              "HResult": {
                "type": "Int32",
                "value": "-2146233088"
              },
              "StackTrace": {
                "type": "String",
                "value": "<scrubbed>"
              }
            }
          }
        },
        "arguments": {
          "originalDepth": {
            "type": "Int32",
            "value": "5"
          },
          "currentDepth": {
            "type": "Int32",
            "value": "5"
          },
          "this": {
            "type": "ExceptionReplayController",
            "value": "ExceptionReplayController"
          }
        }
      }
    },
    "probe": {
      "id": "<scrubbed>",
      "version": 1,
      "location": {
        "method": "exceptionReplayRecursionHelper",
        "type": "weblog.ExceptionReplayController"
      }
    },
    "stack": [
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursion",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 28
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware+<Invoke><scrubbed>",
        "lineNumber": 0
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware.Invoke",
        "lineNumber": 0
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "exceptionHash": "a72525ef-dc75-3a29-abc5-e7f2574a18ab",
    "exceptionId": "<scrubbed>",
    "frameIndex": "5",
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "duration": "<scrubbed>",
    "language": "dotnet"
  },
  {
    "captures": {
      "return": {
        "staticFields": {
          "Empty": {
            "type": "EmptyResult",
            "value": "EmptyResult"
          }
        },
        "throwable": {
          "message": "recursion exception depth 5",
          "type": "System.Exception",
          "stacktrace": [
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "<runtime>": "<scrubbed>"
            }
          ]
        },
        "locals": {
          "@exception": {
            "type": "Exception",
            "value": "Exception",
            "fields": {
              "Message": {
                "type": "String",
                "value": "recursion exception depth 5"
              },
              "InnerException": {
                "type": "Exception",
                "isNull": "true"
              },
              "HelpLink": {
                "type": "String",
                "isNull": "true"
              },
              "Source": {
                "type": "String",
                "value": "app"
              },
              "HResult": {
                "type": "Int32",
                "value": "-2146233088"
              },
              "StackTrace": {
                "type": "String",
                "value": "<scrubbed>"
              }
            }
          }
        },
        "arguments": {
          "originalDepth": {
            "type": "Int32",
            "value": "5"
          },
          "currentDepth": {
            "type": "Int32",
            "value": "4"
          },
          "this": {
            "type": "ExceptionReplayController",
            "value": "ExceptionReplayController"
          }
        }
      }
    },
    "probe": {
      "id": "<scrubbed>",
      "version": 1,
      "location": {
        "method": "exceptionReplayRecursionHelper",
        "type": "weblog.ExceptionReplayController"
      }
    },
    "stack": [
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursion",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 28
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware+<Invoke><scrubbed>",
        "lineNumber": 0
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware.Invoke",
        "lineNumber": 0
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "exceptionHash": "a72525ef-dc75-3a29-abc5-e7f2574a18ab",
    "exceptionId": "<scrubbed>",
    "frameIndex": "4",
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "duration": "<scrubbed>",
    "language": "dotnet"
  },
  {
    "captures": {
      "return": {
        "staticFields": {
          "Empty": {
            "type": "EmptyResult",
            "value": "EmptyResult"
          }
        },
        "throwable": {
          "message": "recursion exception depth 5",
          "type": "System.Exception",
          "stacktrace": [
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "<runtime>": "<scrubbed>"
            }
          ]
        },
        "locals": {
          "@exception": {
            "type": "Exception",
            "value": "Exception",
            "fields": {
              "Message": {
                "type": "String",
                "value": "recursion exception depth 5"
              },
              "InnerException": {
                "type": "Exception",
                "isNull": "true"
              },
              "HelpLink": {
                "type": "String",
                "isNull": "true"
              },
              "Source": {
                "type": "String",
                "value": "app"
              },
              "HResult": {
                "type": "Int32",
                "value": "-2146233088"
              },
              "StackTrace": {
                "type": "String",
                "value": "<scrubbed>"
              }
            }
          }
        },
        "arguments": {
          "originalDepth": {
            "type": "Int32",
            "value": "5"
          },
          "currentDepth": {
            "type": "Int32",
            "value": "3"
          },
          "this": {
            "type": "ExceptionReplayController",
            "value": "ExceptionReplayController"
          }
        }
      }
    },
    "probe": {
      "id": "<scrubbed>",
      "version": 1,
      "location": {
        "method": "exceptionReplayRecursionHelper",
        "type": "weblog.ExceptionReplayController"
      }
    },
    "stack": [
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursion",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 28
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware+<Invoke><scrubbed>",
        "lineNumber": 0
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware.Invoke",
        "lineNumber": 0
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "exceptionHash": "a72525ef-dc75-3a29-abc5-e7f2574a18ab",
    "exceptionId": "<scrubbed>",
    "frameIndex": "3",
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "duration": "<scrubbed>",
    "language": "dotnet"
  },
  {
    "captures": {
      "return": {
        "staticFields": {
          "Empty": {
            "type": "EmptyResult",
            "value": "EmptyResult"
          }
        },
        "throwable": {
          "message": "recursion exception depth 5",
          "type": "System.Exception",
          "stacktrace": [
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "<runtime>": "<scrubbed>"
            }
          ]
        },
        "locals": {
          "@exception": {
            "type": "Exception",
            "value": "Exception",
            "fields": {
              "Message": {
                "type": "String",
                "value": "recursion exception depth 5"
              },
              "InnerException": {
                "type": "Exception",
                "isNull": "true"
              },
              "HelpLink": {
                "type": "String",
                "isNull": "true"
              },
              "Source": {
                "type": "String",
                "value": "app"
              },
              "HResult": {
                "type": "Int32",
                "value": "-2146233088"
              },
              "StackTrace": {
                "type": "String",
                "value": "<scrubbed>"
              }
            }
          }
        },
        "arguments": {
          "originalDepth": {
            "type": "Int32",
            "value": "5"
          },
          "currentDepth": {
            "type": "Int32",
            "value": "2"
          },
          "this": {
            "type": "ExceptionReplayController",
            "value": "ExceptionReplayController"
          }
        }
      }
    },
    "probe": {
      "id": "<scrubbed>",
      "version": 1,
      "location": {
        "method": "exceptionReplayRecursionHelper",
        "type": "weblog.ExceptionReplayController"
      }
    },
    "stack": [
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursion",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 28
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware+<Invoke><scrubbed>",
        "lineNumber": 0
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware.Invoke",
        "lineNumber": 0
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "exceptionHash": "a72525ef-dc75-3a29-abc5-e7f2574a18ab",
    "exceptionId": "<scrubbed>",
    "frameIndex": "2",
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "duration": "<scrubbed>",
    "language": "dotnet"
  },
  {
    "captures": {
      "return": {
        "staticFields": {
          "Empty": {
            "type": "EmptyResult",
            "value": "EmptyResult"
          }
        },
        "throwable": {
          "message": "recursion exception depth 5",
          "type": "System.Exception",
          "stacktrace": [
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "<runtime>": "<scrubbed>"
            }
          ]
        },
        "locals": {
          "@exception": {
            "type": "Exception",
            "value": "Exception",
            "fields": {
              "Message": {
                "type": "String",
                "value": "recursion exception depth 5"
              },
              "InnerException": {
                "type": "Exception",
                "isNull": "true"
              },
              "HelpLink": {
                "type": "String",
                "isNull": "true"
              },
              "Source": {
                "type": "String",
                "value": "app"
              },
              "HResult": {
                "type": "Int32",
                "value": "-2146233088"
              },
              "StackTrace": {
                "type": "String",
                "value": "<scrubbed>"
              }
            }
          }
        },
        "arguments": {
          "originalDepth": {
            "type": "Int32",
            "value": "5"
          },
          "currentDepth": {
            "type": "Int32",
            "value": "1"
          },
          "this": {
            "type": "ExceptionReplayController",
            "value": "ExceptionReplayController"
          }
        }
      }
    },
    "probe": {
      "id": "<scrubbed>",
      "version": 1,
      "location": {
        "method": "exceptionReplayRecursionHelper",
        "type": "weblog.ExceptionReplayController"
      }
    },
    "stack": [
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursion",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 28
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware+<Invoke><scrubbed>",
        "lineNumber": 0
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware.Invoke",
        "lineNumber": 0
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "exceptionHash": "a72525ef-dc75-3a29-abc5-e7f2574a18ab",
    "exceptionId": "<scrubbed>",
    "frameIndex": "1",
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "duration": "<scrubbed>",
    "language": "dotnet"
  },
  {
    "captures": {
      "return": {
        "staticFields": {
          "Empty": {
            "type": "EmptyResult",
            "value": "EmptyResult"
          }
        },
        "throwable": {
          "message": "recursion exception depth 5",
          "type": "System.Exception",
          "stacktrace": [
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
              "lineNumber": 0
            },
            {
              "<runtime>": "<scrubbed>"
            }
          ]
        },
        "locals": {
          "@exception": {
            "type": "Exception",
            "value": "Exception",
            "fields": {
              "Message": {
                "type": "String",
                "value": "recursion exception depth 5"
              },
              "InnerException": {
                "type": "Exception",
                "isNull": "true"
              },
              "HelpLink": {
                "type": "String",
                "isNull": "true"
              },
              "Source": {
                "type": "String",
                "value": "app"
              },
              "HResult": {
                "type": "Int32",
                "value": "-2146233088"
              },
              "StackTrace": {
                "type": "String",
                "value": "<scrubbed>"
              }
            }
          }
        },
        "arguments": {
          "originalDepth": {
            "type": "Int32",
            "value": "5"
          },
          "currentDepth": {
            "type": "Int32",
            "value": "0"
          },
          "this": {
            "type": "ExceptionReplayController",
            "value": "ExceptionReplayController"
          }
        }
      }
    },
    "probe": {
      "id": "<scrubbed>",
      "version": 1,
      "location": {
        "method": "exceptionReplayRecursionHelper",
        "type": "weblog.ExceptionReplayController"
      }
    },
    "stack": [
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursionHelper",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 46
      },
      {
        "function": "weblog.ExceptionReplayController.exceptionReplayRecursion",
        "fileName": "/app/ExceptionReplayController.cs",
        "lineNumber": 28
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware+<Invoke><scrubbed>",
        "lineNumber": 0
      },
      {
        "function": "Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware.Invoke",
        "lineNumber": 0
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "exceptionHash": "a72525ef-dc75-3a29-abc5-e7f2574a18ab",
    "exceptionId": "<scrubbed>",
    "frameIndex": "0",
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "duration": "<scrubbed>",
    "language": "dotnet"
  }
]