[
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "17"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "17": {
          "arguments": {},
          "locals": {
            "depth": {
              "type": "int",
              "value": "20"
            },
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "19"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "18"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "17"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "16"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "15"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "14"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "13"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "12"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "11"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "10"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "9"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "8"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "7"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "6"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "5"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "4"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "3"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "2"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "22"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "22": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "1"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "24"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 24
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion_helper",
        "lineNumber": 22
      },
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_recursion",
        "lineNumber": 17
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "24": {
          "arguments": {
            "depth": {
              "type": "int",
              "value": "0"
            }
          },
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'recursion exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion",
                "lineNumber": 17
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 22
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_recursion_helper",
                "lineNumber": 24
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exception-id": "<scrubbed>"
  }
]