[
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "64"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "_async_throw",
        "lineNumber": 64
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "64": {
          "arguments": {},
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'async exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_async",
                "lineNumber": 69
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "_async_throw",
                "lineNumber": 64
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exceptionId": "<scrubbed>"
  },
  {
    "id": "<scrubbed>",
    "timestamp": "<scrubbed>",
    "evaluationErrors": [],
    "probe": {
      "id": "<scrubbed>",
      "version": 0,
      "location": {
        "file": "/app/exception_replay_controller.py",
        "lines": [
          "69"
        ]
      }
    },
    "language": "python",
    "stack": [
      {
        "fileName": "/app/exception_replay_controller.py",
        "function": "exception_replay_async",
        "lineNumber": 69
      },
      {
        "<runtime>": "<scrubbed>"
      }
    ],
    "captures": {
      "lines": {
        "69": {
          "arguments": {},
          "locals": {
            "@exception": {
              "type": "Exception",
              "fields": "<scrubbed>"
            }
          },
          "staticFields": "<scrubbed>",
          "throwable": {
            "type": "Exception",
            "message": "'async exception'",
            "stacktrace": [
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "exception_replay_async",
                "lineNumber": 69
              },
              {
                "fileName": "/app/exception_replay_controller.py",
                "function": "_async_throw",
                "lineNumber": 64
              },
              {
                "<runtime>": "<scrubbed>"
              }
            ]
          }
        }
      }
    },
    "duration": "<scrubbed>",
    "exceptionId": "<scrubbed>"
  }
]