{
  "snapshot_0": {
    "duration": "<scrubbed>",
    "error": 1,
    "meta": {
      "_dd.code_origin.frames.0.file": "ExceptionReplayController.java",
      "_dd.code_origin.frames.0.line": "32",
      "_dd.code_origin.frames.0.method": "exceptionReplayInner",
      "_dd.code_origin.frames.0.signature": "()",
      "_dd.code_origin.frames.0.type": "com.datadoghq.system_tests.springboot.ExceptionReplayController",
      "_dd.code_origin.type": "entry",
      "_dd.debug.error.94.snapshot_id": "<scrubbed>",
      "_dd.debug.error.exception_hash": "<scrubbed>",
      "_dd.debug.error.exception_id": "<scrubbed>",
      "_dd.integration": "spring-web-controller",
      "_dd.p.tid": "<scrubbed>",
      "component": "spring-web-controller",
      "env": "system-tests",
      "error.debug_info_captured": "true",
      "error.message": "500 INTERNAL_SERVER_ERROR \"Outer exception\"; nested exception is org.springframework.web.server.ResponseStatusException: 500 INTERNAL_SERVER_ERROR \"Inner exception\"",
      "error.stack": "org.springframework.web.server.ResponseStatusException: 500 INTERNAL_SERVER_ERROR \"Outer exception\"; nested exception is org.spr<scrubbed>",
      "error.type": "org.springframework.web.server.ResponseStatusException",
      "key1": "val1",
      "key2": "val2",
      "language": "jvm",
      "span.kind": "server",
      "thread.name": "<scrubbed>",
      "version": "<scrubbed>"
    },
    "metrics": "<scrubbed>",
    "name": "spring.handler",
    "parentID": "<scrubbed>",
    "resource": "ExceptionReplayController.exceptionReplayInner",
    "service": "weblog",
    "spanID": "<scrubbed>",
    "start": "<scrubbed>",
    "traceID": "<scrubbed>",
    "type": "web"
  }
}